### ISSUE TITLE
Add zh-TW to Lockwise Android

### ISSUE THREAD

**Issue by petercpg** [mozilla-l10n/android-l10n#132]
Please add my locale to an existing product contained within the android-l10n repository (this repository). Note that this request must be approved - or made - by a locale manager.

Product Name: Lockwise Android

Locale Requested: zh-TW

You will be notified here once your locale has been enabled on Pontoon. Please note that actual localization work should then happen through Pontoon [here](https://pontoon.mozilla.org/projects/android-l10n/), and not through pull requests in this repository. A specific link to the Pontoon folder will also be sent here.

For any other Mozilla project localization request (such as Firefox, Firefox for iOS, mozila.org, etc), please follow the standard process that can be found [here](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/teams_projects.html#requesting-a-project).

**Comment by Delphine** [comment]
Thanks for filing this Peter! Since most of the team is off on holidays, I'll have to get to this next week. Thanks for your patience :)

**Comment by petercpg** [comment]
No worries, thank you Delphine, and happy holidays :-)

>
