### ISSUE TITLE
Add [uk] to [Lockwise Android]

### ISSUE THREAD

**Issue by a-polivanchuk** [mozilla-l10n/android-l10n#133]
Please add my locale to an existing product contained within the android-l10n repository (this repository). Note that this request must be approved - or made - by a locale manager.

Product Name:

Locale Requested:

You will be notified here once your locale has been enabled on Pontoon. Please note that actual localization work should then happen through Pontoon [here](https://pontoon.mozilla.org/projects/android-l10n/), and not through pull requests in this repository. A specific link to the Pontoon folder will also be sent here.

For any other Mozilla project localization request (such as Firefox, Firefox for iOS, mozila.org, etc), please follow the standard process that can be found [here](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/teams_projects.html#requesting-a-project).

**Comment by Delphine** [comment]
Thanks for filing this Artem! Since most of the team is off on holidays, I'll have to get to this next week. Thanks for your patience :)

**Comment by Delphine** [comment]
Direct link to strings here: https://pontoon.mozilla.org/uk/android-l10n/all-resources/?tag=fenix&string=196915

You can also access the strings from the tags page: https://pontoon.mozilla.org/projects/android-l10n/tags/

**Comment by a-polivanchuk** [comment]
Thanks, Delphine!
So at the same time, I got also the Fenix activated, right?

**Comment by flodolo** [comment]
>  So at the same time, I got also the Fenix activated, right?

No. Your request was only for Lockwise, so you got that and the shared components.

**Comment by a-polivanchuk** [comment]
Ok, will know that I have to request Fenix additionally.
Thanks!
