### ISSUE TITLE
Add en-GB to Firefox Reality

### ISSUE THREAD

**Issue by IanN-GH** [mozilla-l10n/android-l10n#137]
Please add my locale to an existing product contained within the android-l10n repository (this repository). Note that this request must be approved - or made - by a locale manager.

Product Name:

Locale Requested:

You will be notified here once your locale has been enabled on Pontoon. Please note that actual localization work should then happen through Pontoon [here](https://pontoon.mozilla.org/projects/android-l10n/), and not through pull requests in this repository. A specific link to the Pontoon folder will also be sent here.

For any other Mozilla project localization request (such as Firefox, Firefox for iOS, mozila.org, etc), please follow the standard process that can be found [here](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/teams_projects.html#requesting-a-project).

**Comment by Delphine** [comment]
Done!
All projects can be found  on Pontoon, from the Tags section: https://pontoon.mozilla.org/projects/android-l10n/tags/
