### ISSUE TITLE
Add Lockbox to Shared Android L10n System

### ISSUE THREAD

**Issue by devinreams** [mozilla-l10n/android-l10n#14]
Please add a new Android project to the cross-product Android localization repository (this repository).

- Project Name: Firefox Lockbox
- Project Repository: https://github.com/mozilla-lockbox/lockbox-android/
- Project Team: @sashei @linuxwolf @eliserichards @devinreams (EM) @sandysage (PM) @marniepw (EPM)

# Product in shared l10n system

We've read the [documentation on the mana](https://mana.mozilla.org/wiki/display/FIREFOX/Continuous+Localization+Setup+Process+for+Android) and would like to use

**Separate files**

Our `strings.xml` file gets its own copy in this repository. 

We'll ask to unify that file across versions from master and release branches, allowing for dot releases to be shipped from these localizations, including l10n updates.

https://github.com/mozilla-lockbox/lockbox-android/blob/master/app/src/main/res/values/strings.xml

# First steps taken

https://github.com/mozilla-l10n/android-l10n/projects/6

- [x] Our technical string review was tracked in https://github.com/mozilla-lockbox/lockbox-android/issues/204. That's where we make sure strings have comments to explain parameters to localizers and ambiguous strings are clarified.
- [x] There was then a copy-review completed tracked in https://github.com/mozilla-lockbox/lockbox-android/pull/248
- We've maintained strings with translator comments since then
- [ ] Our initial target market and locale list is matches Firefox's priority locales including:
  - French
  - German
  - Spanish
  - Italian
- [ ] The l10n infrastructure integration tracking is here: https://github.com/mozilla-lockbox/lockbox-android/issues/519

**Comment by devinreams** [comment]
Current usage metrics from Play Store:

![image](https://user-images.githubusercontent.com/49511/55738676-cab84400-59e4-11e9-89f0-39609f017eb9.png)

To help prioritize the languages for translation (added Italian to initial requirements in addition to French, German, Spanish).

Any additions or considerations at this time @sandysage?

**Comment by Delphine** [comment]
Thanks so much for filing this :)
While we wait for the final fixes to strings to get into [#579](https://github.com/mozilla-lockbox/lockbox-android/issues/579) (needed in order to expose strings on Pontoon), could you let us know what your release cadence and timeline currently look like? thanks!

**Comment by devinreams** [comment]
We are planning releases every 2 weeks (or so) to match our sprint cadence (end sprint, QA, then release).

Based on our current backlog, we are not expecting to implement a language picker and be “ready” for translations for at least 1 month (2 sprints).
