### ISSUE TITLE
Add Firefox Reality to Shared Android L10n System

### ISSUE THREAD

**Issue by cvan** [mozilla-l10n/android-l10n#16]
Please add a new Android project to the cross-product Android localization repository (this repository).

Project Name: **Firefox Reality**
Project Repository: **https://github.com/MozillaReality/FirefoxReality**

# Product in shared l10n system

We've read the [documentation on the mana](https://mana.mozilla.org/wiki/display/FIREFOX/Continuous+Localization+Setup+Process+for+Android) and would like to use **separate files** generated from [**`strings.xml`**](https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/values/strings.xml).

# First steps taken

An issue for updating the stale strings for Firefox Reality is tracked in **https://github.com/MozillaReality/FirefoxReality/issues/1072**.

Thank you in advance for your help, and thanks again for all the help getting our localised FxR version 1.1 release out the door.

**Comment by Delphine** [comment]
Thanks so much for filing!
While we wait to set things up, some questions I had in order to best support you was: 
* what is your release cadence and current timelines?
* what is your market target and locale list (maybe this list remains the same)
thank you!

**Comment by cvan** [comment]
^ @jvonitter and @philip-lamb can answer those

thanks @Delphine for super fast response. much appreciated.

**Comment by philip-lamb** [comment]
Hi Delphine, six weekly and much the same locale list but I'll pm you with details. Thanks!

**Comment by Delphine** [comment]
Ok going to summarize the discussion with Phil here, so we're all on the same page. I also have a few more questions.

* Next release is in 5 weeks:
-> I'm afraid this may not leave us with a lot of time for localizing and testing, unfortunately. And we haven't set up the new l10n system for your project yet (and strings aren't all final, IIUC).
What's more, I assume that if the actual release is in 5 weeks, then that means l10n needs to be delivered sooner than that. 
Please let me know what that final "l10n-cut off" date would be.

@Pike: do you agree? Thoughts on all this?

* Most strings are final, and there should be only a handful of new strings:
-> please let us know when you expect these strings to be final, as we can not start work until then. Note that we need to have enough time not only for localizing, but also testing. Seems like this is already very time sensitive. We may have to manage expectations on delivery here.
-> related: do we still have localized Nightly builds that are public and anyone can test using their Android device?

* Language wishlist:
Just adding Russian and Spanish from Spain (es-ES) to the existing list this time around.

* Wishlist for within a 4 month timeframe:
Polish
Dutch
Danish
Finnish
Swedish
Norwegian
Czech
Arabic
Spanish - Latin America (ESM)  -> Phil and I still need to discuss which "flavor" of Spanish to use for this

**Comment by philip-lamb** [comment]
One correction, all defined strings are final, so work can begin anytime.

Is there any other work involved in setting up the automation other than registering the project in the appropriate places in the repo?

**Comment by Delphine** [comment]
Heads-up that I've filed [#1089](https://github.com/MozillaReality/FirefoxReality/issues/1089) with my review.
These aren't blocking us from exposing strings we currently have (note that it seems one is missing?).
We should be able to start exposing these strings to localizers on Pontoon tomorrow (PST). Since there are not that many strings, I am more confident we are now on track :)

For the automation question, I think there are still some missing pieces that we can still tender to manually, but @Pike would be able to give a better update there.

Please do let me know when your ideal deadline for getting the localizations back to you is (I assume a bit earlier than release date, but don't know when). Thanks!

**Comment by philip-lamb** [comment]
Soft freeze for Firefox Reality v1.2 is around May 10th, so anytime in advance of then is good.

**Comment by Delphine** [comment]
Ok thanks, I'll tell them May 9th then

**Comment by Delphine** [comment]
Closing this issue since we've added FxR to Pontoon now!
