### ISSUE TITLE
Add Corsican to Fenix' locale switcher

### ISSUE THREAD

**Issue by Patriccollu** [mozilla-l10n/android-l10n#161]
Hello,

Corsican locale is already available in the **android-l10n** repository (this repository):

[https://pontoon.mozilla.org/co/android-l10n/](https://pontoon.mozilla.org/co/android-l10n/)

But this locale was not activated in **Firefox for Android**.

Product Name: **Fenix**
Locale Requested: **Corsican**

Do I need to do something else in order to use the locale switcher in Fenix?

Thanks,
Patriccollu.

**Comment by flodolo** [comment]
The locale is already available in the language switcher on my phone (as "Corso", given the phone is in Italian). Which version of Firefox Preview are you using, and what's the version number?

**Comment by Delphine** [comment]
I also see "Corse" available since my Firefox Preview is in French. As Flod mentions, please give us the version number you are using, as well as the type of phone you have. Thanks!

**Comment by Patriccollu** [comment]
@Delphine @flodolo 
Hello,

Please can you confirm the following link is the good one to download the application in order to test it?

https://play.google.com/store/apps/details?id=org.mozilla.fenix

Thanks,
Patriccollu.

**Comment by gueroJeff** [comment]
Hi Patriccollu,

Localizers should install this one for testing: https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly The language switcher isn't enabled on the release version yet (what you've linked to).

**Comment by Patriccollu** [comment]
@gueroJeff 
Hi gueroJeff,
Great! Thanks for the link. I will use it.
Patriccollu.
