### ISSUE TITLE
Recently modified Corsican strings not refreshed on Nightly

### ISSUE THREAD

**Issue by Patriccollu** [mozilla-l10n/android-l10n#299]
Hello,

I recently modified several strings for Corsican locale on Pontoon and there are not published on latest Nightly builds.

Here is an example of the modified strings:
![Corsican locale for Fenix - Recent on Pontoon](https://user-images.githubusercontent.com/22452654/102627691-d744e780-4148-11eb-948d-69171471ee0e.PNG)

They have been properly stored on GitHub:
![Corsican locale for Fenix - Latest history data](https://user-images.githubusercontent.com/22452654/102621975-abbdff00-4140-11eb-896c-112e63df6691.PNG)

But here is the screen displayed today on Android:
![Corsican locale for Fenix - Settings - Search ](https://user-images.githubusercontent.com/22452654/102627363-63a2da80-4148-11eb-8b7e-2d293f3fd0b1.jpg)

As well as the About screenshot:
![Corsican locale for Fenix - About Firefox Nightly ](https://user-images.githubusercontent.com/22452654/102627364-643b7100-4148-11eb-9a2b-abf60cac9d38.jpg)

Please can you check?

Cheers,
Patriccollu.

**Comment by Delphine** [comment]
This should have been fixed, so closing.
Please re-open if needed! thank you!
