### ISSUE TITLE
Add [locale] to [product]

### ISSUE THREAD

**Issue by fastang** [mozilla-l10n/android-l10n#302]
Please add my locale to an existing product contained within the android-l10n repository (this repository). Note that this request must be approved - or made - by a locale manager.

Product Name:

Locale Requested:

You will be notified here once your locale has been enabled on Pontoon. Please note that actual localization work should then happen through Pontoon [here](https://pontoon.mozilla.org/projects/android-l10n/), and not through pull requests in this repository. A specific link to the Pontoon folder will also be sent here.

For any other Mozilla project localization request (such as Firefox, Firefox for iOS, mozila.org, etc), please follow the standard process that can be found [here](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/teams_projects.html#requesting-a-project).

**Comment by Delphine** [comment]
Hello @fastang - it seems there isn't the locale or product listed here. Are you interested in localizing Fenix - or another product?
Which language would you like to translate in? Thank you

**Comment by Delphine** [comment]
Closing due to lack of information and response. Please re-open if this is still needed, adding further information. Thank you
