### ISSUE TITLE
Adding translator/manager role to "kaa" locale

### ISSUE THREAD

**Issue by Delphine** [mozilla-l10n/android-l10n#590]
This [contributor](https://pontoon.mozilla.org/contributors/cK66tJ-fQ8o97VIiAgkFmRwvGNw/) recently contacted me to translate mobile projects in [Karakalpak](https://pontoon.mozilla.org/kaa/).
I noticed that right now, no one has any rights for this locale on Pontoon in order to approve any suggestions. Which means we need to upgrade some users rights, so that they can actually have their work published.
I am therefore suggesting to add Ali as manager for this locale. They will therefore be able to approve suggestions over the board across projects.
Francis from Common Voice has asked me to give a heads-up to @beknazar about this. Not sure what the current situation is, and if you also need to be upgraded with rights on Pontoon.
Feel free to reach out with any questions whatsoever. Thank you

**Comment by Delphine** [comment]
While I wait for a reply, I will add Ali as translator for Firefox for Android only.

**Comment by Delphine** [comment]
Hi @beknazar. Just wanted to give a heads-up that I will add the contributor as a manager for Common Voice, unless there is any reason not to.
Let me know! thanks

**Comment by beknazar** [comment]
Hi @Delphine 
Sounds good!

**Comment by Delphine** [comment]
Thanks for letting me know! cheers

**Comment by Delphine** [comment]
@beknazar: Just to confirm I've added Ali as a manager for "kaa" locale. Not sure if you also work on those translations or not. Currently, only Ali can publish their work and review translations. 
If there are [other folks](https://pontoon.mozilla.org/kaa/contributors/) who I should give actual translation rights to because of the quality of their translations, please let me know.
