### ISSUE TITLE
License comments are lost when moving files from firefox-android

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/android-l10n#645]
Originally noticed in https://github.com/mozilla-mobile/firefox-android/pull/1637

CCing a bunch of people, because there are a ton of moving parts here @gabrielluong @Delphine @mathjazz @eemeli 

The en-US files loose the license comment when moved to android-l10n. See ([this file](https://github.com/mozilla-l10n/android-l10n/blob/main/mozilla-mobile/android-components/components/browser/engine-system/src/main/res/values/strings.xml)), compared to the file in [the firefox-android repository](https://github.com/mozilla-mobile/firefox-android/blob/main/android-components/components/browser/engine-system/src/main/res/values/strings.xml).

Original file

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
<resources>
```

android-l10n file

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
```

The en-US file is not copied, it's [parsed by compare-locales here](https://github.com/mozilla-l10n/android-l10n/blob/main/.github/scripts/import_strings.py#L94-L102). I did this to avoid a diff with the previous infrastructure (android-l10n-tooling). Which means compare-locales strips out that comment.

Possible ways out:
* Replace parse+serialize with a dumb copy. There will be a diff for some strings, but what I don't know is what Pontoon is going to do with that comment: is it going to be serialized when a locale is updated?
* Update compare-locales to special case comments for licenses.

I also don't know if that comment is the right way to go. For example, I see XML files in mozilla-central that have the comment at the very beginning of the file. That would probably make the compare-locales solution easier, but I don't know if that even works for Android.

**Comment by flodolo** [comment]
You can see a diff here if we copy instead of parsing+serializing
https://github.com/mozilla-l10n/android-l10n/compare/test_copy_xml?expand=1

Some looks like things that should be fixed in firefox-android to start with (like HTML entities, wrong comments, license header not starting on a new line, maybe some escaping).

@mathjazz 
Would it be safe to try changing one file for en-US (adding the comment), to see if Pontoon maintains that comment? Or can you test that locally?

**Comment by eemeli** [comment]
At least currently compare-locales ignores all comments outside the `<resources>` element, and does not provide special handling for license comments in Android strings.xml files, as it does for some other formats.

But why would we need to keep the license comment in this transform? I'm not a lawyer, but [MPLv2](https://www.mozilla.org/en-US/MPL/2.0/) differentiaties and defines "Source Code Form" as "the form of the work preferred for making modifications", while "Executable Form [...] means any form of the work other than Source Code Form". The license comment is not required for Executable Form, as long as the Source Code Form (with the license) is also available.

So even though the output is still human-readable XML, I think it's more appropriate to consider it as Executable Form given that that's how we're actually using it, and that we explicitly prefer for source modifications to be made to the source from which it's processed by our tooling.

**Comment by flodolo** [comment]
These are a few things that I think would make sense to fix, independently from this
https://github.com/mozilla-mobile/firefox-android/compare/main...flodolo:firefox-android:strings_fixes?expand=1

Not sure about use of plain quotes (compare-locales output) vs `&quot;` (android files)

**Comment by Delphine** [comment]
This issue has been really quiet for a couple of weeks. I propose we close this when we're all back next week, if no one hollers in the meantime.
CC @gabrielluong and @mathjazz, in case you'd want to chime in before then

**Comment by mathjazz** [comment]
> @mathjazz
> Would it be safe to try changing one file for en-US (adding the comment), to see if Pontoon maintains that comment? Or can you test that locally?

Pontoon uses compare-locales to parse and serialize string.xml files. As Eemeli pointed out, that means Pontoon WILL NOT maintain the license comment.

**Comment by Delphine** [comment]
I am unclear on what we're doing with this at this point. Seems like nothing?
Can we close this?

**Comment by flodolo** [comment]
I'm going to close, and we can revisit if needed.

This requires investigation with legal, to understand if having the license in each file is a requirement (and I think that would be on the mobile's team).

If that's the case, then we need to find bandwidth to work on Pontoon and compare-locales, because automation in this repository is not the problem.

@gabrielluong 
I think fixing this would be useful independently
https://github.com/mozilla-mobile/firefox-android/compare/main...flodolo:firefox-android:strings_fixes?expand=1
