### ISSUE TITLE
Wrong external link in FirefoxReality/app/src/main/res/values/strings.xml

### ISSUE THREAD

**Issue by jakobkappel** [mozilla-l10n/android-l10n#70]
security_options_drm_content: `Play DRM-Controlled Content (<a href="http://somesite.com/">Learn More</a>)`

There are much better places to learn about DRM than http://somesite.com ;)

Note that all localizations seem to have copied the URL

**Comment by Delphine** [comment]
Thanks Jakob, seems like this fell through the cracks! I'll send this out to the team right away

**Comment by Delphine** [comment]
Seems like the team is still working on that feature and haven't exposed it yet - and will update the string very soon with the correct URL. I'll close this for now, but please refile if this stays this way with the next  batch of  strings! thanks :)
