### ISSUE TITLE
Wrong grammatical number in string for Firefox Reality?

### ISSUE THREAD

**Issue by jakobkappel** [mozilla-l10n/android-l10n#99]
![Skærmbillede 2019-10-25 kl  13 31 22](https://user-images.githubusercontent.com/3586612/67568409-695f8480-f72c-11e9-8f72-5052fd9d430b.png)

appears to refer to

![Skærmbillede 2019-10-25 kl  13 31 53](https://user-images.githubusercontent.com/3586612/67568421-6f556580-f72c-11e9-91df-b129ab05afed.png)
 
If that is the case "them" should probably be "it".

**Comment by jakobkappel** [comment]
https://github.com/mozilla-l10n/android-l10n/blob/master/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml#L1065

**Comment by Delphine** [comment]
CC @jvonitter for input.
Thanks for filing Jakob :)

**Comment by flodolo** [comment]
Updated link
https://github.com/mozilla-l10n/android-l10n/blob/master/MozillaReality/FirefoxReality/app/src/main/res/values/strings.xml#L1462-L1467

**Comment by keianhzo** [comment]
@flodolo As there can be multiple popups at the same time I think the correct would be:
`%1$s prevented pop-ups from this site`
I guess we need to update the key as this string is already translated, right?

**Comment by flodolo** [comment]
>  I guess we need to update the key as this string is already translated, right?

Yes, that's correct.

**Comment by flodolo** [comment]
Fixed in https://github.com/mozilla-l10n/android-l10n/commit/a0d5a48dc8984c49181a7c647a91a82a6863ae20
